# Generated by Django 6.0.1 on 2026-02-02 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='reference',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='total_voucher',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
