# Generated by Django 6.0.1 on 2026-02-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoin', '0002_vouchercode_reference_alter_promo_total_voucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercode',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoin.promo'),
        ),
    ]
