# Generated by Django 6.0.1 on 2026-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoin', '0003_alter_vouchercode_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount'), ('free_shipping', 'Free shipping')], default='fixed', max_length=32),
        ),
    ]
